version = 1

[[annotations]]
path = [
    ".gitignore",
    ".pre-commit-config.yaml",
    ".secrets.baseline",
    "docs/superpowers/plans/2026-07-03-routedef-package-implementation.md",
    "docs/superpowers/specs/2026-07-03-routedef-package-architecture-design.md",
    "README.md",
    "VERSION",
    "pyproject.toml",
    "src/routedef/py.typed",
]
SPDX-FileCopyrightText = "Copyright (c) 2026 provide.io llc"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "Copyright (c) 2026 provide.io llc"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    ".coverage",
    ".mypy_cache/**",
    ".mutmut-cache/**",
    "mutants/**",
    ".pytest_cache/**",
    ".ruff_cache/**",
    "**/__pycache__/**",
    "dist/**",
    "htmlcov/**",
]
SPDX-FileCopyrightText = "Copyright (c) 2026 provide.io llc"
SPDX-License-Identifier = "Apache-2.0"
